### ISSUE TITLE
Implement force_update config variable

### ISSUE THREAD

**Issue by SchmDan** [robmarkcole/HASS-Deepstack-face#11]
Hey,

first of all thank you for this cool integration!
Could you please add the ability, that an event is fired on each successful response no matter if a face is detected or recognised?
The case is, that i want immediately send the current camera picture after the last one is processed. The config entry "scan_interval" is too static for me.
Another possibility could be to implement this as a feature instead of firing an event. Means sending the new camera image directly when the response is here and add an config entry for that.

Thanks in advance!

**Comment by robmarkcole** [comment]
You should use the events already in home assistant, thanks

**Comment by SchmDan** [comment]
There's no event fired when the state doesn't changes. That's exactly is the problem. I found a solution which could easily integrated. Just add the function "force_update" in the class "FaceClassifyEntity". I did this and everything works as expected. The Function looks like this:
<img width="560" alt="Screenshot 2020-06-10 at 08 19 06" src="https://user-images.githubusercontent.com/48385869/84233685-1556b400-aaf3-11ea-8121-cd03696cbb16.png">
Maybe this can be set trough a config entry?

Thanks!

**Comment by robmarkcole** [comment]
I am a bit surprised by this since [process_faces](https://github.com/home-assistant/core/blob/8f3c84b349cd8ee92dcb4cce69749a2c1ac66eab/homeassistant/components/image_processing/__init__.py#L180) does not have any dependency on the state. Which event do you need fired?

**Comment by SchmDan** [comment]
I don't know how you get to that function. My proposal is to add force_update somewhere like here: [https://github.com/robmarkcole/HASS-Deepstack-face/blob/master/custom_components/deepstack_face/image_processing.py#L231](url). The return value could be set through a config entry. If False, nothing of the behaviour changes. If True an event gets fired on each update of the state, even if the state hasn't changed. And with this event I trigger the next analysis with the current picture of my camera.

**Comment by robmarkcole** [comment]
Can you clarify which event you are expecting to see

**Comment by SchmDan** [comment]
With "force_update" return True, you get a "state_changed" event, even if the state is the same. That's what I use in my automation as a trigger.
`trigger:`
`    - platform: state`
`      entity_id: image_processing.face_detection`

Works like charm.

**Comment by robmarkcole** [comment]
OK that makes sense to me. Not sure if this change would impact other peoples automations, one way to find out..!

**Comment by SchmDan** [comment]
After some investigation i changed my mind since my first post. I think that's a better solution for the problem.
Exactly, miflora sensor implements this as i would love to have it.

Thanks!
Can this also be done in [HASS-Deepstack-object](https://github.com/robmarkcole/HASS-Deepstack-object)?

**Comment by robmarkcole** [comment]
done. This actually should be default behaviour IMO
