### ISSUE TITLE
Basic plan only supports 5 faces

### ISSUE THREAD

**Issue by eifinger** [robmarkcole/HASS-Deepstack-face#2]
Hi,
I wanted to try your component because in the README you stated `Choose the basic plan which will give us unlimited access for one installation`.

However on the website it says for the Basic Plan `Face Recognition API (5 Faces)`

Which of them is true?

Thanks!

**Comment by robmarkcole** [comment]
Hi
I believe this changed since I added that line to the readme, please see https://deepstack.cc/#pricing
