### ISSUE TITLE
Possible face attributes

### ISSUE THREAD

**Issue by RobHofmann** [robmarkcole/HASS-Deepstack-face#23]
Hi,

I'm curious if this integration will allow me to detect attributes for a face.

What i mean by this is, is for example if the eyes are closed.

I'm looking to implement a babymonitor with this if thats possible.

Looking forward to your response!

Kind regards,
Rob

**Comment by robmarkcole** [comment]
Hi Rob
that would be a feature request on Deepstack, which is not yet OSS.
Cheers

**Comment by robmarkcole** [comment]
close for now
