### ISSUE TITLE
Update for image_processing.face_detection fails

### ISSUE THREAD

**Issue by Gio76** [robmarkcole/HASS-Deepstack-face#26]
Hi @robmarkcole,

I've had the Deepstack-face custom component (installed via HACS) installed for a while and it has always worked flawlessly. Today it just stopped working, not sure why. I constantly get the error message **_'Update for image_processing.office_face_detection fails'_**

This is the full error message from Home Assistant's log:

```Logger: homeassistant.helpers.entity
Source: custom_components/deepstack_face/image_processing.py:210 
First occurred: 2:49:33 PM (1 occurrences) 
Last logged: 2:49:33 PM

Update for image_processing.office_face_detection fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 132, in async_update
    await self.async_process_image(image.content)
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 112, in async_process_image
    return await self.hass.async_add_executor_job(self.process_image, image)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deepstack_face/image_processing.py", line 210, in process_image
    self._dsface.recognise(image)
AttributeError: 'DeepstackFace' object has no attribute 'recognise'
```

Also, since this issue has started occurring, I am unable to teach new faces:

![image](https://user-images.githubusercontent.com/26906928/102708287-7518ed80-42d4-11eb-8484-2db051b31f1b.png)

This is the image_processing YAML in HA:

```
- platform: deepstack_face
  ip_address: 192.168.86.5
  port: 5000
  api_key: !secret deepstack_api_key
  save_file_folder: /config/deepstack/
  save_timestamped_file: True
  source:
    - entity_id: camera.office_cam
      name: office_face_detection
```
```
homeassistant:
  allowlist_external_dirs: 
    - /config/deepstack/
```

This is my HA installation:

- version: 2020.12.1
- installation_type: Home Assistant OS
- dev: false
- hassio: true
- docker: true
- virtualenv: false
- python_version: 3.8.6
- os_name: Linux
- os_version: 5.4.84
- arch: x86_64
- HASS-Deepstack-face 0.6

I have tried deleting the Docker container and re-installing it with all the below variations and the issue still occurs every time:

- sudo docker run -e VISION-FACE=True -e VISION-DETECTION=True -e API-KEY="*****" -v localstorage:/datastore -p 5000:5000 --name deepstack -d deepquestai/deepstack:noavx
- sudo docker run -e VISION-FACE=True -e VISION-DETECTION=True -e API-KEY="*****" -v localstorage:/datastore -p 5000:5000 --name deepstack -d deepquestai/deepstack:latest
- sudo docker run -e VISION-FACE=True -e VISION-DETECTION=True -e API-KEY="*****" -v localstorage:/datastore -p 5000:5000 --name deepstack -d deepquestai/deepstack

I have tried without 'sudo', with port 80:5000, with and without VISION-DETECTION. Nothing helped. When launching the component in Docker everything seems to be working correctly:

![image](https://user-images.githubusercontent.com/26906928/102708189-b9f05480-42d3-11eb-85f8-dc4bd52f32ff.png)

Any assistance is greatly appreciated!

**Comment by Gio76** [comment]
Possibly related to #25
Forgot to mention that the object detection component works perfectly

**Comment by robmarkcole** [comment]
The issue here is that the `Deepstack-python` dependency is upgraded to 0.8 in object detection but still on 0.6 in face and scene, will update those ASAP

**Comment by Gio76** [comment]
Thanks for the prompt reply @robmarkcole. Great job as always!

**Comment by koldogut** [comment]
Error persists in ver 3.7

**Comment by robmarkcole** [comment]
If you are using Deepstack object as well that needs to be updated to lastest as well.

**Comment by koldogut** [comment]
Im using it through HACS, so it should be already updated with ver 3.7, shouldn't it? Deepstack docker image is also up-to-date.

**Comment by robmarkcole** [comment]
I am not sure how frequently HACS updates its info

**Comment by koldogut** [comment]
Reinstalled Face Recognition from HACS and working back again, thank you Rob!
