### ISSUE TITLE
Question regarding setup

### ISSUE THREAD

**Issue by LordNex** [robmarkcole/HASS-Deepstack-face#28]
I've setup several image processors in the past and in my testing I've decided upon this on a Jetson Nano to do real time facial recognition for secure entry and notification on my house. I e got the Nano ordered but thought I'd give it a try just through HACS to see how well it would run on my i5 laptop with VMWare and Home Assistant OVA running. 

Adding it was easy enough add I only added 2 camera entities for it to scan. I can see the entities in HA and they currently show "Unknown" like what you show in the setup docs. But if I or anyone goes in front of the camera, the state for the processor entity never changes. I've successfully tried it faces, well I didn't receive any error anyway. 

So my question is, do I need to run this completely separate from HA to get it to work? It seems adding the component through HACS and adding the proper configuration.yaml entries isn't working for me and I haven't yet setup a separate docker server outside of what HA has built in. Am I missing something as I've been able to get DOODS, Facebox, and TensorFlow all setup before without any issue. Thanks in advance for all your hard work and let me know if there is anything I can do in the future to contribute

**Comment by robmarkcole** [comment]
Hi you have not given any info about how you are running Deepstack, or provided any error messages. 
Since this is not a code issue please raise on the HA forum thread.
Thanks
