### ISSUE TITLE
deepstack_teach_face

### ISSUE THREAD

**Issue by carnagebek** [robmarkcole/HASS-Deepstack-face#38]
i got this error while running home assistant and deepstack in docker:

Falha ao chamar o serviço image_processing/deepstack_teach_face. required key not provided @ data['name']

But i have already tried insert this config in the home assistant service deepstack_teach_face:

service: deepstack_teach_face
name: Test
file_path: /config/test.jpeg

PS: sorry for the language, im from Brazil.

**Comment by robmarkcole** [comment]
`required key not provided @ data['name']` - maybe you didnt enter it correctly
