### ISSUE TITLE
Error 500 for Face detection, works for object detection

### ISSUE THREAD

**Issue by stumpk** [robmarkcole/HASS-Deepstack-face#39]
Hi,

Great plugins! Thank you for all the effort. I have been trying to implement these following the guides from the Everything Smart Home Tutorials. I'm running Home Assistant on a ubuntu VM and have installed Deepstack in a container using Portainer on the HA VM. The object detection works perfectly, but I am getting an error on the face detection/recognition. 
Here are the logs from the container for a pass on the object but error on the face:
![image](https://user-images.githubusercontent.com/16841104/111829802-65e11600-88aa-11eb-9a68-fae716e24e50.png)

When I look into the stderr.txt file in the logs on the container I get the following:

![image](https://user-images.githubusercontent.com/16841104/111834966-937d8d80-88b1-11eb-9ae4-674d8171260d.png)

my HA config is like this:

![image](https://user-images.githubusercontent.com/16841104/111835056-b14af280-88b1-11eb-812a-863195391d33.png)

can you please point me in the direction of what I am missing?

**Comment by robmarkcole** [comment]
That is a deepstack error - it cant find some files (I think the model files). PLease raise on deepstack forum

**Comment by stumpk** [comment]
Thanks, Robin. I did try posting there but I never got a response. Someone
else was having the same error with a windows install, but doesn't look
like there is a resolution. I'm trying Facebox for now until they can
figure this out. I've tried reinstalling DeepStack several times and in
several ways and it all appears to do the same thing.
