### ISSUE TITLE
HomeAssistant - Deepstack GPU v.2021.02.1 - Face detection strange image_processing output

### ISSUE THREAD

**Issue by dimitribellini** [robmarkcole/HASS-Deepstack-face#41]
Dear Mark,
thanks for your great Deepstack Integration, during my test seems that everything is working. Face recognition seems ok from both side Deepstack and HA but the output of image_processing is this:
`faces:
  - name: dimitri
    confidence: 55.067
    bounding_box:
      height: 0.36
      width: 0.165
      y_min: 0.258
      x_min: 0.308
      y_max: 0.619
      x_max: 0.473
    prediction:
      confidence: 0.55067384
      userid: dimitri
      y_min: 279
      x_min: 592
      y_max: 668
      x_max: 908
    entity_id: image_processing.face_counter
total_faces: null
total_matched_faces: 0
matched_faces: {}
last_detection: 2021-04-29_17-36-01
friendly_name: face_counter
device_class: face`

I have "registered" my face and from deepstack curl request seems ok (right confidence value) but from the image_processing i still saw "total_faces=0".
The picture grabbed from the image scan seems also work, i can saw the red square on my face.
Do you know why? Something is changed on Deepstack restapi?
Thanks

**Comment by DivanX10** [comment]
**Tell me, how did you manage to register a person? Are you from HA running this or what? How is everything set up? Where is Deepstack running?** 
Скажите, а как вы смогли зарегистрировать лицо? Вы из ХА это запускаете или как? Как у вас все настроено? Где запущен Deepstack?

**I ran into a problem and can't register the image. Described the details [here](https://community.home-assistant.io/t/face-and-person-detection-with-deepstack-local-and-free/92041/1210?u=divanx10)**
Я столкнулся проблемой и не могу зарегистрировать изображение. Подробности описал **[тут](https://community.home-assistant.io/t/face-and-person-detection-with-deepstack-local-and-free/92041/1210?u=divanx10)**

**Please share your settings and how did you manage to register the image?**
Пожалуйста поделитесь своими настройками и как вам удалось зарегистрировать изображение?

**Comment by dimitribellini** [comment]
Hi DivanX10,
to register my faces i have used "https://github.com/robmarkcole/deepstack-ui" as a docker container but you can also use the simple "curl" way.
es.:curl -X POST -F 'image=@image1.JPG' -F 'userid="Fred"' 'http://MYIP:83/v1/vision/face/register' 
and to test if is working:
es.: curl -X POST -F 'image=@image1.JPG' 'http://MYIP:83/v1/vision/face/recognize'  

About deepstack is running on a container with an NVIDIA Quadrat P400 as OS i have used Centos8

The Deepstack HomeAssistant configuration is the same of the youtube video you have posted.

**Comment by DivanX10** [comment]
**I tried to do this. The image cannot be loaded. How do I still correctly specify the code?**
Попробовал сделать так.  Не удается загрузить изображение. Как все таки правильно указать код?
```
curl -X POST -F 'image=http://192.168.1.110:8123/config/www/deepstack/snapshots/face_detect_latest.jpg' -F "userid=Divan" http://192.168.1.200:5100/v1/vision/face/register

curl -X POST -F 'image=http://192.168.1.110:8123/local/deepstack/snapshots/face_detect_latest.jpg' -F "userid=Divan" http://192.168.1.200:5100/v1/vision/face/register
```

![image](https://user-images.githubusercontent.com/64090632/116714785-c3569f80-a9de-11eb-9102-96aff1096d3c.png)

**Comment by DivanX10** [comment]
**The issue is resolved. I left the answer [here](https://community.home-assistant.io/t/face-and-person-detection-with-deepstack-local-and-free/92041/1211?u=divanx10)**

Вопрос решен. Ответ я оставил [**здесь**](https://community.home-assistant.io/t/face-and-person-detection-with-deepstack-local-and-free/92041/1211?u=divanx10)

**Comment by dimitribellini** [comment]
> Dear Mark,
> thanks for your great Deepstack Integration, during my test seems that everything is working. Face recognition seems ok from both side Deepstack and HA but the output of image_processing is this:
> `faces:
> 
> * name: dimitri
>   confidence: 55.067
>   bounding_box:
>   height: 0.36
>   width: 0.165
>   y_min: 0.258
>   x_min: 0.308
>   y_max: 0.619
>   x_max: 0.473
>   prediction:
>   confidence: 0.55067384
>   userid: dimitri
>   y_min: 279
>   x_min: 592
>   y_max: 668
>   x_max: 908
>   entity_id: image_processing.face_counter
>   total_faces: null
>   total_matched_faces: 0
>   matched_faces: {}
>   last_detection: 2021-04-29_17-36-01
>   friendly_name: face_counter
>   device_class: face`
> 
> I have "registered" my face and from deepstack curl request seems ok (right confidence value) but from the image_processing i still saw "total_faces=0".
> The picture grabbed from the image scan seems also work, i can saw the red square on my face.
> Do you know why? Something is changed on Deepstack restapi?
> Thanks

I have finally understood that i need more "picture" of my face for a better match.. so is not a problem of your integration. sorry
I will close the issue.

**Comment by DivanX10** [comment]
```
I have finally understood that i need more "picture" of my face for a better match.. so is not a problem of your integration. sorry
I will close the issue
```

I also noticed that the more you load the image, the more accurately it detects the face. I uploaded more than 10 photos per person and the system became better able to detect them. When there were less than 10 photos per person, there were far more erroneous facial definitions than there are now.

Я тоже заметил, что чем больше загружаешь изображении, тем точнее определяет лицо. Я загрузил более 10 фотографии на каждого человека и система стала лучше определять. Когда было менее 10 фотографии на каждого человека, то ошибочного определения лица было куда больше, чем сейчас.
