### ISSUE TITLE
One face, one name, and different angles

### ISSUE THREAD

**Issue by DivanX10** [robmarkcole/HASS-Deepstack-face#44]
It is not possible to train the system so that it can detect faces from different angles. For example, I took photos of the face in 5 versions, straight, at an angle of 45 and 90 degrees. I upload a photo and assign each photo one name. When I make a check for each photo, some photos forget the names that I previously assigned a name to. For example, I uploaded a photo with a face where the face looks straight and assigned the name Divan, then I uploaded a photo at an angle of 45 degrees and assigned the name Divan, then I uploaded a photo at 90 degrees and also assigned the name Divan. When you upload a photo of a face that looks directly into the camera, the system no longer recognizes it, it recognizes the last photo. I understand that you can only upload one photo for one face, right, or is it still possible to train the system of one face from different angles?

Не получается обучить систему, чтобы она могла определять лица в разных ракурсах. Например сделал фотографии лица в 5 вариантах, прямо, под углом 45 и 90 градусов. Загружаю фото и присваиваю каждому фото одно имя. Когда делаю проверку по каждому фото, то на некоторых фото забываются имена, которым я ранее присвоил имя. Например загрузил фото с лицом, где лицо смотрит прямо и присвоил имя Divan, далее загрузил фото под углом в 45 градусов и присвоил имя Divan, потом загрузил фото под 90 градусов и также присвоил имя Divan. При проверки, загрузив фото лица, которое смотрит прямо в камеру система уже не опознает, она опознает последнее фото. Я так понимаю, что можно загрузить только одно фото для одного лица, верно или все же можно обучить систему одного лица с разных ракурсов?

**Comment by robmarkcole** [comment]
This is a deepstack question please ask on their forum
