### ISSUE TITLE
HA Entity state not updating

### ISSUE THREAD

**Issue by cigas4** [robmarkcole/HASS-Deepstack-face#45]
Hi, I am trying to run deepstack face recognition on my HA. 
HASS is running on rpi4, and deepstack is running on another rpi4. Issue what I am facing at the moment is that I dont get any recognition update on entity inside HA. State of this entity always stays Unknown. However if I check deepstack on another rpi4 I can see my recognition request from HA, so not sure what is wrong. Are there any log files on HA or on deepstack side?
So ether recognition is not accuring or recognition result is not geting back to HA.
I am also running frigate container together with deepstack on same rpi4, not sure if it can have some effect. 

HA config:
  

> - platform: deepstack_face
>     ip_address: 192.168.31.13
>     port: 80
>     timeout: 5
>     detect_only: False
>     save_file_folder: /config/www/snapshots/
>     save_timestamped_file: True
>     save_faces: True
>     save_faces_folder: /config/www/faces/
>     show_boxes: True
>     source:
>       - entity_id: camera.entrance_person
>         name: deepstack_face_recognition

<img width="411" alt="Screenshot 2021-05-15 at 15 08 07" src="https://user-images.githubusercontent.com/54658863/118376587-7f17f180-b5d1-11eb-9f5d-94dd7a5de701.png">

<img width="691" alt="Screenshot 2021-05-15 at 15 06 45" src="https://user-images.githubusercontent.com/54658863/118376580-76bfb680-b5d1-11eb-919e-01d729e8e323.png">

**Comment by hristo-atanasov** [comment]
I'm running HASS Deepstack face on docker on windows PC and I have the same problem.

**Comment by DivanX10** [comment]
Watch this [video](https://youtu.be/74b2bQDn1xA), maybe this will help you
Посмотрите это [видео](https://youtu.be/74b2bQDn1xA), возможно это вам поможет

**Comment by cigas4** [comment]
Also when I start deepstack it says "visit local host to activate Deepstack". Maybe it needs some kind of activation to work? Unfortunately cant find any info on activation.. If I enter random key it says "Can't reach activation server".

<img width="2553" alt="Screenshot 2021-05-17 at 08 57 11" src="https://user-images.githubusercontent.com/54658863/118439285-55a0b800-b6ee-11eb-859f-dbd5ba2e6195.png">

**Comment by DivanX10** [comment]
You have installed deepstack version 1.0, which means you have it installed
on raspberry.  I personally encountered this when I tried to install it on
a raspberry.  Deepstack has dropped support for raspberry.  You need to
install the latest version, and this is version 2 and it is already
activated

Вы установили deepstack версии 1.0, а значит у вас это установлено на
raspberry. Сам лично сталкивался с этим, когда пытался установить на
raspberry. Deepstack прекратил поддержку для raspberry. Нужно ставить
последнюю версию, а это версия 2 и она уже активированная

пн, 17 мая 2021 г., 9:01 Andrius ***@***.***>:

**Comment by cigas4** [comment]
> You have installed deepstack version 1.0, which means you have it installed on raspberry. I personally encountered this when I tried to install it on a raspberry. Deepstack has dropped support for raspberry. You need to install the latest version, and this is version 2 and it is already activated Вы установили deepstack версии 1.0, а значит у вас это установлено на raspberry. Сам лично сталкивался с этим, когда пытался установить на raspberry. Deepstack прекратил поддержку для raspberry. Нужно ставить последнюю версию, а это версия 2 и она уже активированная пн, 17 мая 2021 г., 9:01 Andrius ***@***.***>:
> […](#)

Hi, Thanks for info. Is version 2 even available for PI?

**Comment by cigas4** [comment]
> Unfortunately for raspberry, images are no longer made. At the moment there is only this deepstack v 1.0 image that requires activation. You can install deepstack v 2 on windows, linux, docker К сожалению для raspberry больше не делают образы. На данный момент есть только этот образ deepstack v 1.0 который требует активации. Вы можете установить deepstack v 2 на windows, linux, docker пн, 17 мая 2021 г., 10:08 Andrius ***@***.***>:
> […](#)

I am running docker on same rpi4. Also tried installing deepstack docker container, but there was some issues running it.. Only this method with image was working. Maybe need to check it again.

For installation I used this script:

> #!/bin/bash
> echo "Setting Up Prerequisites."
> sudo apt-get update
> sudo apt-get install redis-server -y
> sudo apt-get install libatlas-base-dev libjpeg-dev -y
> py=python3.7
> $py --version
> py_check=$?
> if [ $py_check -ne 0 ]
> then
> py=python3.5
> fi
> sudo $py -m pip install numpy --upgrade
> status=$?
> if [ $status -ne 0 ]
> then
> exit
> fi
> sudo $py -m pip install scipy --upgrade
> status=$?
> if [ $status -ne 0 ]
> then
> exit
> fi
> sudo $py -m pip install pillow --upgrade
> status=$?
> if [ $status -ne 0 ]
> then
> exit
> fi
> sudo $py -m pip install redis --upgrade
> status=$?
> if [ $status -ne 0 ]
> then
> exit
> fi
> echo "Getting DeepStack"
> sudo rm deepstack.deb
> wget https://deepquest.sfo2.digitaloceanspaces.com/deepstack/deepstack.deb
> echo "Installing DeepStack"
> sudo dpkg -i deepstack.deb
> sudo rm deepstack.deb
> status=$?
> if [ $status -eq 0 ]
> then
> echo 'DeepStack installed, run with sudo deepstack start "VISION-SCENE=True"'
> fi

**Comment by DivanX10** [comment]
Read on the [forum deepstack](https://forum.deepstack.cc/t/rasberry-pi-and-positions-of-items-reported-wrong/401/6)
Почитайте на [форуме deepstack](https://forum.deepstack.cc/t/rasberry-pi-and-positions-of-items-reported-wrong/401/6)

The answer of the author himself is that pi will no longer be supported and they go completely to docker
Ответ самого автора, что pi больше не будет поддерживаться и они уходят полностью в docker
![image](https://user-images.githubusercontent.com/64090632/118485980-bf868500-b721-11eb-8728-185d0b2600cf.png)
https://github.com/VorlonCD/bi-aidetection/issues/65#issuecomment-713512196

**Comment by robmarkcole** [comment]
Is this still an issue on latest deepstack image?

**Comment by robmarkcole** [comment]
stale closing
