### ISSUE TITLE
Teach face service ( home assistance )

### ISSUE THREAD

**Issue by malajam** [robmarkcole/HASS-Deepstack-face#47]
hi 
i am trying to add faces but i am getting this error : 

Failed to call service image_processing.deepstack_teach_face. extra keys not allowed @ data['sequence'][0]['file_path']. Got '/config/www/faces/moh_1.jpg' extra keys not allowed @ data['sequence'][0]['name']. Got 'mohammed'

the service code :  
service: image_processing.deepstack_teach_face
name: mohammed
file_path: /config/www/faces/moh_1.jpg

there is no spaces and yamle is typed not copy & paste 
adding { or " or ' give me the same error

**Comment by mi4mac** [comment]
It has to look like that ...

service: image_processing.deepstack_teach_face
data:
  name: name
  file_path: your_path

**Comment by malajam** [comment]
Hi
thanks for your reply and your time

i tried it but i am getting another error related to  Directory ( the path is correct , i do not know where is the mistake ) + extra key not allowed :

Failed to call service image_processing.deepstack_teach_face. expected dict for dictionary value @ data['sequence'][0]['data']. Got None extra keys not allowed @ data['sequence'][0]['file_path']. Got '/config/faces/moh_1.jpg' extra keys not allowed @ data['sequence'][0]['name']. Got 'mohammed'

the code :

service: image_processing.deepstack_teach_face
data:
name: mohammed
file_path: /config/faces/moh_1.jpg

i tried many formats and all returned the same error 

service: image_processing.deepstack_teach_face
data:
"name": "mohammed"
"file_path": "/config/faces/moh_1.jpg"

and also :

service: image_processing.deepstack_teach_face
data:
name: 'mohammed'
file_path: '/config/faces/moh_1.jpg'

and :

service: image_processing.deepstack_teach_face
data:
name: "mohammed"
file_path: "/config/faces/moh_1.jpg"

**Comment by paulmro** [comment]
same here :(

**Comment by ASTPlatinum** [comment]
I'm not the only one then, same here.

**Comment by interbiznw** [comment]
Yea not working here either, but everyone posting YAML in non code blocks is not likely helpful as the formatting can be removed.

to post blocks of code such as yaml use 3 taps on the back ticks key   ` and yaml. like this: 
![image](https://user-images.githubusercontent.com/16450422/131255835-0b90a67e-5168-4d28-a11d-353be62e176b.png)
(before the number one on top row)  then type code, then another 3 taps of the backticks key

it will put the code in proper formatting and look like this
![image](https://user-images.githubusercontent.com/16450422/131255845-ffb3cac4-6690-4853-8931-efb5e76e84d4.png)


with an end result of :

```yaml
service: imaginary_service.run_me
data:
  name: 'name here'
  file_path: '/path/goes/here/image.jpg'
  ```
