### ISSUE TITLE
403 Error on Docker Container

### ISSUE THREAD

**Issue by ralphmackinder** [robmarkcole/HASS-Deepstack-face#48]
I have installed the component as per the readme, I have Deppstack Face running on a docker container via portainer on HA. 

Everything seems like it should be working, I can reach deepstack via locaip:port (get the splash screen) and can confirm that when I attempt to call service from HA it reaches Deepstack. 

But Im getting a 403 error that I cant resolve.  it applies to the scan and face learning services. 

Example Log output from container: 

[GIN] 2021/05/24 - 23:22:51 | 403 |      86.952µs |    192.168.1.64| POST     /v1/vision/face/register
[GIN] 2021/05/24 - 23:38:24 | 403 |      29.444µs |    192.168.1.64| POST     /v1/vision/face/register
[GIN] 2021/05/24 - 23:40:18 | 403 |      28.929µs |    192.168.1.64| POST     /v1/vision/face/recognize

Example log output from supervisor portainer add on log in HA: 

2021/05/24 16:31:08 [ERROR] [http,client] [message: unexpected status code] [status_code: 403]

Any advice would be welocme. Ive spent most of today trying to identify the issue, let alone resolve it!

**Comment by DivanX10** [comment]
Watch this [video](https://youtu.be/74b2bQDn1xA), maybe it will help you.

**Comment by interbiznw** [comment]
403 is unauthorized, check if you set a API KEY ON deepstack and or in the homeassistant config. make sure they match

**Comment by robmarkcole** [comment]
what @interbiznw said

**Comment by ps1x** [comment]
I resolved this issue for me by setting - VISION-FACE=True environment variable, notice True is starting with capital letter.
